dist: bionic

language: python
cache: pip

before_script:
  - pip install -r test_requirements.txt

script: tox

matrix:
  include:

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=linting

notifications:
  email: false
