---

sudo: false
dist: bionic

language: python
cache: pip

before_script:
  - pip install -r test_requirements.txt

script: tox

matrix:
  include:

    - python: "3.7"
      env: TOXENV=py37

    # Linters

    - python: "3.7"
      env: TOXENV=linting

notifications:
  email: false
