---

sudo: false
dist: bionic

language: python
cache: pip

before_script:
  - pip install tox tox-docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script: tox

matrix:
  include:

    - python: "3.7"
      env: TOXENV=py37

    # Linters

    - python: "3.7"
      env: TOXENV=linting

notifications:
  email: false
